from __future__ import annotations

import argparse
import json
import sys
from datetime import date, datetime
from pathlib import Path

import openpyxl


ROOT_DIR = Path(__file__).resolve().parents[1]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from src.connections.xlsx_connection import COLUMN_ALIASES, normalize_status  # noqa: E402


BASE_KEYS = [
    "email",
    "password",
    "otp_email",
    "otp_pass",
    "otp_imap_host",
    "crane_container_id",
    "crane_container_name",
    "crane_status",
    "frida_device_id",
    "frida_device_name",
    "gold_status",
    "chiu_status",
    "status",
    "notes",
    "credit_card_number",
    "credit_card_exp",
    "credit_card_cvv",
    "onepiece_shop_name",
    "onepiece_area",
]


def normalize_header(value: object) -> str:
    text = str(value or "").strip().lower()
    return COLUMN_ALIASES.get(text, text)


def cell_text(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, datetime):
        return value.date().isoformat()
    if isinstance(value, date):
        return value.isoformat()
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value).strip()


def read_config_xlsx() -> str:
    config_path = ROOT_DIR / "config.json"
    if not config_path.exists():
        return ""
    try:
        data = json.loads(config_path.read_text(encoding="utf-8"))
    except Exception:
        return ""
    return str(data.get("xlsx_path") or "").strip()


def read_config_sheet() -> str:
    config_path = ROOT_DIR / "config.json"
    if not config_path.exists():
        return "Accounts"
    try:
        data = json.loads(config_path.read_text(encoding="utf-8"))
    except Exception:
        return "Accounts"
    return str(data.get("active_sheet") or "Accounts").strip() or "Accounts"


def choose_sheet(wb, sheet_name: str):
    if sheet_name in wb.sheetnames:
        return wb[sheet_name]
    if "Accounts" in wb.sheetnames:
        return wb["Accounts"]
    if "Mail" in wb.sheetnames:
        return wb["Mail"]
    return wb[wb.sheetnames[0]]


def load_row(xlsx_path: Path, sheet_name: str, row_number: int | None, email: str = "") -> tuple[dict, int, str]:
    wb = openpyxl.load_workbook(xlsx_path, data_only=True, read_only=True)
    try:
        ws = choose_sheet(wb, sheet_name)
        rows = ws.iter_rows(values_only=True)
        try:
            header_row = next(rows)
        except StopIteration:
            raise RuntimeError(f"Sheet {ws.title!r} is empty.")

        headers = [normalize_header(cell) for cell in header_row]
        wanted_email = email.strip().lower()

        for index, row in enumerate(rows, start=2):
            if row_number is not None and index != row_number:
                continue
            record = {}
            for pos, header in enumerate(headers):
                if not header:
                    continue
                value = cell_text(row[pos]) if pos < len(row) else ""
                if header in record and not value:
                    continue
                record[header] = value
            row_email = str(record.get("email") or "").strip()
            if not row_email:
                continue
            if wanted_email and row_email.lower() != wanted_email:
                continue
            if row_number is None and not wanted_email:
                status = normalize_status(record.get("status", "PENDING"))
                gold_status = normalize_status(record.get("gold_status", record.get("status", "PENDING")))
                chiu_status = normalize_status(record.get("chiu_status", "PENDING"))
                if chiu_status in ("SUCCESS", "FAIL_NO_RETRY") or (
                    status not in ("PENDING", "FAILED") and gold_status not in ("PENDING", "FAILED")
                ):
                    continue
            return record, index, ws.title
    finally:
        wb.close()

    if row_number is not None:
        raise RuntimeError(f"No usable data found at row {row_number}.")
    if email:
        raise RuntimeError(f"No usable row found for email {email!r}.")
    raise RuntimeError("No PENDING/FAILED row with email was found.")


def profile_from_record(record: dict) -> dict:
    profile = {}
    for key in BASE_KEYS:
        value = str(record.get(key) or "").strip()
        if value:
            profile[key] = value
    profile["row"] = {key: value for key, value in record.items() if str(value or "").strip()}
    return profile


def write_profile_js(profile: dict, out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(profile, ensure_ascii=False, indent=2)
    js = (
        "// Generated by scripts/chiu_profile_from_excel.py\n"
        "(function loadChiuExcelProfile(){\n"
        f"  const profile = {payload};\n"
        "  globalThis.__CHIU_PROFILE__ = profile;\n"
        "  function apply(){\n"
        "    if (typeof setChiuProfile === 'function') {\n"
        "      setChiuProfile(profile);\n"
        "      console.log('[chiu-profile] loaded from Excel: ' + (profile.email || '(no email)'));\n"
        "      return;\n"
        "    }\n"
        "    setTimeout(apply, 250);\n"
        "  }\n"
        "  apply();\n"
        "})();\n"
    )
    out_path.write_text(js, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Export one Excel row into a Frida-loaded Chiu profile JS file.")
    parser.add_argument("--xlsx", default=read_config_xlsx(), help="Path to XLSX. Defaults to config.json xlsx_path.")
    parser.add_argument("--sheet", default=read_config_sheet(), help="Sheet name. Defaults to config active_sheet.")
    parser.add_argument("--row", type=int, default=None, help="Excel row number to export, e.g. 2.")
    parser.add_argument("--email", default="", help="Find row by email instead of first pending row.")
    parser.add_argument("--out", default=str(ROOT_DIR / "agents" / "current_profile.js"), help="Output JS file.")
    parser.add_argument("--print-only", action="store_true", help="Print profile JSON without writing JS.")
    args = parser.parse_args()

    if not args.xlsx:
        raise SystemExit("Missing --xlsx and config.json does not contain xlsx_path.")
    xlsx_path = Path(args.xlsx).expanduser()
    if not xlsx_path.exists():
        raise SystemExit(f"XLSX not found: {xlsx_path}")

    record, row_number, sheet = load_row(xlsx_path, args.sheet, args.row, args.email)
    profile = profile_from_record(record)
    metadata = {"xlsx": str(xlsx_path), "sheet": sheet, "row": row_number}

    if args.print_only:
        print(json.dumps({"profile": profile, "source": metadata}, ensure_ascii=False, indent=2))
        return 0

    out_path = Path(args.out).expanduser()
    write_profile_js(profile, out_path)
    print(f"Wrote: {out_path}")
    print(json.dumps({"profile": profile, "source": metadata}, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
